### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by luukvdmeer** [spnethack/spnethack#1]
@Robinlovelace @loreabad6 When doing a Stackoverflow answer (https://stackoverflow.com/questions/57833905/how-to-convert-a-list-of-sf-spatial-points-into-a-routable-graph/58096728#58096728) I found out some igraph/tidygraph behaviour that I think is important to mention in the blogpost (about the ID structure of the nodes after creating a subgraph).

Therefore, I did a small update to the post.

Could you do a new pull request to r-spatial, @Robinlovelace ? I think that is also a good way to remind Edzer!

**Comment by Robinlovelace** [comment]
Can do - would like to get a 👍 from @edzer first - happy for this to go in this week Edzer (I can update the date also)? Thanks Lucas.

**Comment by edzer** [comment]
It's high on my list to release this, but I can wait a few days if you tell me to do so.

**Comment by Robinlovelace** [comment]
OK, great. How's about I update this afternoon/evening with a view to releasing it tomorrow?

Thanks @edzer

**Comment by Robinlovelace** [comment]
Heads-up @luukvdmeer, @loreabad6 and @edzer here's the latest version, hopefully good to go!

https://github.com/r-spatial/r-spatial.org/pull/44

**Comment by Robinlovelace** [comment]
Heads-up all it's there: https://www.r-spatial.org/r/2019/09/26/spatial-networks.html

Note: the shortest path figures are missing. They should be in there, my bad. Will update the figures.

**Comment by Robinlovelace** [comment]
Fixed now so closing. Plan to tweet it later today, feel free to go ahead and put it out there @luukvdmeer excellent work!

**Comment by luukvdmeer** [comment]
Thank you @Robinlovelace, good to see that people seem to like it ;)

**Comment by Robinlovelace** [comment]
For sure. A question I'm wondering: what to do next? 

I'm working with @agila5 on spatial networks and seeing the possibilities and limitations of `SpatialLinesNetwork` and wondering whether I should shift to import `sfnetworks`. Any further ideas on +s vs -s of the approach in your package (other than it's not on CRAN yet!)?

Any thoughts on how you'd like to take this forward welcome - you thinking of packaging it up for CRAN?

I think this problem should be solved at a high level after some thought and the blog post is a big step in that direction, congrats on getting it out there!

**Comment by luukvdmeer** [comment]
I opened a new issue for this, in the sfnetworks repository: https://github.com/luukvdmeer/sfnetworks/issues/4
